# AUTOGENERATED! DO NOT EDIT! File to edit: ../../notebooks/ipynb/04_config_api.ipynb.

# %% auto 0
__all__ = ['SupportedModelProviders', 'OllamaProviderConfig', 'OpenAIProviderConfig', 'AnthropicProviderConfig',
           'BedrockProviderConfig', 'LoggingConfig', 'LiquidAgentConfig']

# %% ../../notebooks/ipynb/04_config_api.ipynb 1
from enum import StrEnum, auto

from pydantic import BaseModel

# %% ../../notebooks/ipynb/04_config_api.ipynb 3
class SupportedModelProviders(StrEnum):
    """Supported model providers."""

    OLLAMA = auto()
    OPENAI = auto()
    ANTHROPIC = auto()
    BEDROCK = auto()

# %% ../../notebooks/ipynb/04_config_api.ipynb 4
class OllamaProviderConfig(BaseModel):
    """Configuration for Ollama models."""

    host: str
    model: str

# %% ../../notebooks/ipynb/04_config_api.ipynb 5
class OpenAIProviderConfig(BaseModel):
    """Configuration for OpenAI models."""

    pass

# %% ../../notebooks/ipynb/04_config_api.ipynb 6
class AnthropicProviderConfig(BaseModel):
    """Configuration for Anthropic models."""

    pass

# %% ../../notebooks/ipynb/04_config_api.ipynb 7
class BedrockProviderConfig(BaseModel):
    """Configuration for Bedrock models."""

    pass

# %% ../../notebooks/ipynb/04_config_api.ipynb 8
class LoggingConfig(BaseModel):
    """Configuration for logging."""

    logfile_path: str = ""

# %% ../../notebooks/ipynb/04_config_api.ipynb 9
class LiquidAgentConfig(BaseModel):
    """Configuration for the Liquid Agent."""

    preferred_model: SupportedModelProviders
    ollama: OllamaProviderConfig | None = None
    openai: OpenAIProviderConfig | None = None
    anthropic: AnthropicProviderConfig | None = None
    bedrock: BedrockProviderConfig | None = None
    logger: LoggingConfig | None = None
