# AUTOGENERATED! DO NOT EDIT! File to edit: ../../notebooks/ipynb/07_utils.ipynb.

# %% auto 0
__all__ = ['get_chat_model']

# %% ../../notebooks/ipynb/07_utils.ipynb 1
from .chat_model.base import ChatModelProtocol
from .chat_model.ollama import OllamaChatModel
from .config import LiquidAgentConfig, SupportedModelProviders

# %% ../../notebooks/ipynb/07_utils.ipynb 3
def get_chat_model(
    config: LiquidAgentConfig, provider: str | None = None
) -> ChatModelProtocol:
    """
    Retrieves a chat model based on the provided configuration.

    Parameters
    ----------
    config : LiquidAgentConfig
        The configuration object containing the preferred model and related settings.
    provider : str, optional
        The specific provider to use. Defaults to None.

    Returns
    -------
    ChatModelProtocol
        The instantiated chat model.

    Raises
    ------
    ValueError
        If the preferred model is not supported.
    """
    # Override preferred_model if provider is given
    if provider is not None:
        config.preferred_model = SupportedModelProviders(provider)

    if config.preferred_model == SupportedModelProviders.OLLAMA:
        assert config.ollama is not None
        return OllamaChatModel(config.ollama)

    raise ValueError("chat model not supported")
